### ISSUE TITLE
eastwest routes combined with custom-routes not working as expected

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#1024]
**Describe the bug**

There is no clear idea what should happen, but the main route should always be created in the eastwest routes. This is not the case anymore.

**To Reproduce**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  namespace: default
  annotations:
    zalando.org/skipper-routes: |
       redirect: PathRegexp("/mypath") -> redirectTo(308, "https://red.example.org/") -> <shunt>;
spec:
  rules:
  - host: "app-default.example.org"
    http:
      paths:
      - path: /
        backend:
          serviceName: app-svc
          servicePort: 80
```

This ingress will only create the redirect from the custom route in eastwest routes (`app.default.skipper.cluster.local`)

**Expected behavior**

Create all routes that make sense also for eastwest, which is of course in this case the route to `app-svc`.
