### ISSUE TITLE
Oauth Token Introspection Filter

### ISSUE THREAD

**Issue by justinrcs** [zalando/skipper#1026]
**Describe the bug**
After attempting to setup a Kubernetes ingress route using the oauthTokenintrospectionAllClaims filter, Skipper reports an invalid token when setting up the route and subsequent requests to the ingress results in a 404.

**To Reproduce**
Using Skipper, latest: v.0.10.203

1. Setup ingress route with the following:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "test"
  labels:
    application: test
  annotations:
    kubernetes.io/ingress.class: "skipper"
    zalando.org/skipper-filter: oauthTokenintrospectionAllClaims("https://okta.issuer.url", "claim-name")
spec:
  rules:
  - host: "test.host.com"
    http:
      paths:
      - backend:
          serviceName: "test-app"
          servicePort: 80
```
https://okta.issuer.url is a base url provided by Okta Oauth provider; this is the root url that contains /.well-known/openid-configuration as specified by the Skipper documentation for Token Introspection.
 
2. Tailing skipper ingress controller log:

```
[APP]time="2019-04-09T18:32:28Z" level=info msg="route settings, update, route: kube_default__test__test_host_com____test_app: Host(/^test[.]host[.]com$/) -> oauthTokenintrospectionAllClaims(\"https://okta.issuer.url", \"claim\") -> \"http://100.112.0.2:9090\""
[APP]time="2019-04-09T18:32:28Z" level=info msg="route settings received"
[APP]time="2019-04-09T18:32:28Z" level=error msg="failed to process route (kube_default__test__test_host_com____test_app): invalid token"
[APP]time="2019-04-09T18:32:28Z" level=info msg="route settings applied"
```
**Expected behavior**
The route itself to be setup and requests made without a token to return a 401 or with a valid token to return 200

**Observed behavior**
The route is not available, Skipper returns a 404

Are we missing a setup step?

**Comment by szuecs** [comment]
Can you check if `https://okta.issuer.url/.well-known/openid-configuration` returns an introspection endpoint with json key `introspection_endpoint`?
A problem could be that the rfc draft defined it as "optional" and your provider does not return this field.

The error message says that the problem is within the route processing and it is most probably in [CreateFilter](https://github.com/zalando/skipper/blob/master/filters/auth/tokenintrospection.go#L162) which is processed with all the arguments your provide. Maybe you can add some log messages to understand better what the problem is if `introspection_endpoint` is returned in  `https://okta.issuer.url/.well-known/openid-configuration`.

**Comment by justinrcs** [comment]
Thanks - I traced the issue here:

filters/auth/intospectiontoken.go

calls jsonGet with a blank access token:

```
func getOpenIDConfig(issuerURL string) (*openIDConfig, error) {
  ...
  err = jsonGet(u, "", &cfg, http.DefaultClient, nil, nil, "")
```
in 
filters/auth/authclient.go
this sets the header regardless of whether the accesstoken is set or not:

```
func jsonGet(
	url *url.URL,
	accessToken string,
	doc interface{},
	client *http.Client,
	tracer opentracing.Tracer,
	parentSpan opentracing.Span,
	childSpanName string,
) error {
...
req.Header.Set(authHeaderName, authHeaderPrefix+accessToken)  
```  

Since it's blank, the OAuth provider responds with "Invalid Token"

My temp fix was to just check to see if this header needs to be set

```
if len(accessToken) > 0 {
      req.Header.Set(authHeaderName, authHeaderPrefix+accessToken)    
    }
```

**Comment by szuecs** [comment]
Looks like it makes sense. :)
Do you want to create a pull request?

**Comment by justinrcs** [comment]
Done - thanks

**Comment by justinrcs** [comment]
Came across a limitation with using the TokenIntrospection endpoint:
When attempting to validate/decode an Access token, the AuthClient is making a post to the Introspection endpoint

filters/auth/authclient.go
```
func jsonPost(
	u *url.URL,
	auth string,
	doc *tokenIntrospectionInfo,
	client *http.Client,
	tracer opentracing.Tracer,
	parentSpan opentracing.Span,
	spanName string,
) error {
        body := url.Values{}
	body.Add(tokenKey, auth)
        req, err := http.NewRequest("POST", u.String(), strings.NewReader(body.Encode()))
	
```

The OAuth provider either needs ClientID and ClientSecret passed in as additional POST parameters or as a base64-encoded Basic Authorization header. 

I'd propose the client id and secret be passed in as environment variables and added to the request if they are set.

**Comment by szuecs** [comment]
No problem with that. Maybe it makes more sense to have it in the filter configuration instead, similar to oidc* filters? 
Filter would be possible to configure per route, env/flag would be global.

**Comment by justinrcs** [comment]
I can look at adding both options.  I agree providing it as part of the filter config gives more flexibility and allows Skipper to run in environments where multiple OAuth providers are supported. Including as part of the config, however, exposes the OAuth secret in plain text and if you have many routes you're going to be duplicating that info.

**Comment by szuecs** [comment]
We do not really use ENV vars for anything right now, so this would be a bit unexpected behavior, but I understand your point. Maybe we can read the secret from a file, and use a Kubernetes secret to pass the client-secret? 
To understand better your point: Do you have to set client-id, client-secret to validate the inflight token?

If you want to work on this, I would suggest creating a new filter that has the modified parameters and behavior to not break other use cases.

@aryszka what do you think about ENV vars configuring filter params?

**Comment by justinrcs** [comment]
Ok I was going the route of passing the Kubernetes secrets in via env vars:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: skipper-ingress
...
spec:
  containers:
    name: skipper:
    ...
       env:
        - name: OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: skipper-oauth
              key: client_id
        - name: OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: skipper-oauth
                key: client_secret 
```

I can modify this to read the secrets from a volume mount if you prefer.

Yes, the introspection endpoint requires some kind of authorization to validate / decode the inflight token:
[https://tools.ietf.org/html/rfc7662#page-4](https://tools.ietf.org/html/rfc7662#page-4)

The spec mentions two methods, a Bearer token or Basic Auth and the specific provider we're utilizing (Okta) either requires Basic Auth or the client-id and client-secret passed in as form parameters. It seemed like Basic Auth would be the most compatible. 

I can create a new filter - do you have a naming preference?
