### ISSUE TITLE
OAuth Scope Validation is returning an incorrect response code

### ISSUE THREAD

**Issue by irishshagua** [zalando/skipper#1035]
## Describe the bug
If you use any of the oauthTokeninfo* family of filters on a route and the token is successfully authenticated but does not pass the scope check, a 401 response code is returned. I think this should return a 403 to signify the difference between an authentication issue and an authorization issue.

### To Reproduce
An example 
**K8s Resources**:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoping-auth-example
  labels:
    application: scoping-auth-example
spec:
  replicas: 1
  selector:
    matchLabels:
      application: scoping-auth-example
  template:
    metadata:
      labels:
        application: scoping-auth-example
    spec:
      containers:
      - name: scoping-auth-example
        image: jmalloc/echo-server:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: scoping-auth-example
  labels:
    application: scoping-auth-example
spec:
  selector:
    application: scoping-auth-example
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    zalando.org/skipper-filter: oauthTokeninfoAllScope("uid", "service.scope")
    zalando.org/skipper-predicate: Path("/api/resource") && Method("GET")
  name: scoping-auth-example
spec:
  rules:
  - host: scoping-auth-example.example.com
    http:
      paths:
      - backend:
          serviceName: scoping-auth-example
          servicePort: http
``` 

**Sample Requests**
```
curl -i https://scoping-auth-example.example.com/api/resource
HTTP/2 401
date: Tue, 16 Apr 2019 10:41:34 GMT
content-length: 0
server: Skipper
www-authenticate: auth.example.com

curl -i -H "Authentication: Bearer $TOKEN"  https://scoping-auth-example.example.com/api/resource
HTTP/2 401
date: Tue, 16 Apr 2019 10:42:01 GMT
content-length: 0
server: Skipper
www-authenticate: auth.example.com
```

**Expected behavior**
I would expect a 401 for the first request and a 403 for the second request

**Observed behavior**
I get a 401 for both scenarios
