### ISSUE TITLE
rainbow traffic switching flap route matches

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#1266]
If you specify more than 2 versions of the same ingress, like in the example you get unepected results:

```
kind: Ingress
metadata:
  name: my-app
  labels:
    application: my-app
  annotations:
    zalando.org/backend-weights: |
      {"my-app-1": 50, "my-app-2": 25, "my-app-3": 25}
```

This will result in 3 routes:

```
r1: Traffic(0.5) -> "my-app-1" // 50%
r2: Traffic(0.5) -> "my-app-2" // 50% out of the lasting 50% -> 25%
r3: * -> "my-app-3" // rest -> 25%
```

This looks good, but we now have r1 and r2 with the same priority for the routing match!
Therefore r1 and r2 can flap, which results in sometimes having unexpected r1 25% and r2 50%.
