### ISSUE TITLE
Skipper doesn't strip port portion from host header when matching routes

### ISSUE THREAD

**Issue by shamil** [zalando/skipper#1281]
**Describe the bug**
Skipper doesn't strip port portion from host header when matching routes

**To Reproduce**
Add context, for example:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: skipper
  name: example
  namespace: default
spec:
  rules:
  - host: app.example.tld
    http:
      paths:
      - backend:
          serviceName: example
          servicePort: 80
```

2. http request with headers (truncate your secrets)

Works

```
curl -s https://app.example.tld:443
```

Doesn't work (I get 404)

```
curl -s -H "Host: app.example.tld:443" https://app.example.tld:443
```

**Expected behavior**

The route should match regardless whether the port specified in `Host` header, it is fully RFC valid (https://tools.ietf.org/html/rfc2616#section-14.23)

**Observed behavior**

When `Host` header contains a port portion the route no longer matched
