### ISSUE TITLE
filter oauthOIDCUserInfo not found

### ISSUE THREAD

**Issue by universam1** [zalando/skipper#1284]
**Describe the bug**
running latest version and several filter are not found
registry.opensource.zalan.do/pathfinder/skipper:v0.11.27

**To Reproduce**

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard-demo-load-test
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kube-alb
    zalando.org/skipper-filter: oauthOIDCUserInfo("https://oidc-provider.example.com", "client_id", "client_secret", "http://target.example.com/subpath/callback", "email profile", "name email picture")
```
logs:
```
[APP]time="2020-01-23T17:44:10Z" level=info msg="route settings, update, route: kube_default__kuard_demo_load_test______kuard_demo_load_test: Host(/^monitor.org$/) -> oauthOIDCUserInfo(\"https://oidc-provider.example.com\", \"client_id\", \"client_secret\", \"http://target.example.com/subpath/callback\", \"email profile\", \"name email picture\") -> \"http://172.31.47.159:8080\""                                     
[APP]time="2020-01-23T17:44:10Z" level=info msg="route settings received"                                                                                                                                             
[APP]time="2020-01-23T17:44:10Z" level=error msg="failed to process route (kube_default__kuard_demo_load_test__monitoorg____kuard_demo_load_test): filter not found: 'oauthOIDCUserInfo'"
```

same applies to `oauthOIDCAnyClaims`:
```
filter not found: 'oauthOIDCAnyClaims'"
```
