### ISSUE TITLE
[Question] skipper Ingress resources examples

### ISSUE THREAD

**Issue by kolbis** [zalando/skipper#1285]
I am looking for examples for defining ingress resources for skipper.
Beside the following [documentation](https://opensource.zalando.com/skipper/kubernetes/ingress-usage/), where can I get more examples? 

For instance, how would you create ingress resources for the following routes:
path1: *  -> "https://www.example.org";
path2: Path("/home") -> "https://www.google.com";
dynamicPath1: Path("/catalog/*")  -> setPath("") -> <dynamic>;

**Comment by szuecs** [comment]
@kolbis In case of ingress skipper reads from ingress objects and I don't see how the first routes can be expressed. For routes without host definition you would need to create a backend, which will get default traffic.

```
spec:
  backend:   # default backend
    serviceName: mybackend
    servicePort: 80
  rules:
  - http:  # drop this if you want to have `*` instead of Path("/home")
      paths:
      - path: "/home"
```

You can read more documentation about ingress in https://kubernetes.io/docs/reference/generated/kubernetes-api/ . If you want to proxy to an external URL, you can use https://kubernetes.io/docs/concepts/services-networking/service/#externalname as backend, but there was a bug in our issue tracker, that we did not fixed yet.

Your 3rd route is wrong:
- Path() has no single "**, if you want to match everything below "/catalog/", use `PathSubtree("/catalog/")` instead. See also https://opensource.zalando.com/skipper/reference/predicates/#path
- Backend definition can not be empty. To understand which backend you want to use https://opensource.zalando.com/skipper/reference/backends/. If you want to use another backend from ingress you have to use custom routes https://opensource.zalando.com/skipper/kubernetes/ingress-usage/#custom-routes
