### ISSUE TITLE
bearerinjector filter requires absolute secret path

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/skipper#1436]
**Describe the bug**
1. Documentation [states](https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#bearerinjector) `bearerinjector` filter uses filename as argument while in fact it requires absolute secret path (i.e. it should be `bearerinjector("/tmp/secrets/write-token")` )
2. [Another part of documentation](https://github.com/zalando/skipper/blob/master/docs/reference/egress.md#example-bearer-injection) also uses filename instead of absolute path and also uses wrong token name in example (uses `bearerinjector("sec1")` while it should be `bearerinjector("/tmp/secrets/mytoken")`)

**To Reproduce**
Here is a sidecar container k8s deployment definition that works (note it uses absolute path as `bearerinjector` argument):
```yaml
        - name: egress
          image: "registry.opensource.zalan.do/pathfinder/skipper:v0.11.105"
          args:
            - skipper
            - -address=:9999
            - -credentials-paths=/meta/credentials
            - -credentials-update-interval=10s
            - -inline-routes
            - |
              myService: Path("/ws/myService")
                -> enableAccessLog()
                -> bearerinjector("/meta/credentials/my_service-token-secret")
                -> "http://myService.example.com";
              default: * -> enableAccessLog() -> status(503) -> <shunt>;
          ports:
            - containerPort: 9999
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              memory: 20Mi
          volumeMounts:
            - name: my-credentials
              mountPath: /meta/credentials
              readOnly: true
```

**Expected/Observed behavior**
According to documentation `bearerinjector` argument should be filename.
Token injection does not work if filename is uses instead of absolute path.

**Proposal**
1. It might be not that bad to actually use absolute path: skipper supports multiple `-credentials-paths` arguments (e.g. `-credentials-paths=/meta/credentials,/etc`) and in case when just filename is used it is not clear which secret would be used if there is a filename clash in credentials' paths.
therefore the proposal is to update documentation to reflect that absolute secret path should be used as `bearerinjector` argument.

2. `bearerinjector` filter does nothing in case secret does not exist, instead it should write a error log message to simplify debugging.
