### ISSUE TITLE
Can we use a startup parameters in an ingress rule?

### ISSUE THREAD

**Issue by kenotsolutions** [zalando/skipper#1498]
Hi,

I could not find my question answer in the repository.  Can we use a startup parameter in an ingress rule? for example, I would like to use this disable-http-keepalives for only below ingress rule. I can disable it from Kubernetes skipper deployment but If I can I would like to disable keep alive for only this ingress rule not for all the k8s env.

I put it under annotations but it did not work there.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    disable-http-keepalives: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
    kubernetes.io/ingress-class: skipper-https
    proxy-preserve-host: "true"
    zalando.org/skipper-routes: |
      test: PathRegexp("/test") -> setResponseHeader("X", "bar") -> inlineContent("<html><body>hello</body></html>") ->     name: test-ingress
  namespace: dev-test
spec:
  rules:
  - host: dev.test.com
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
```
