### ISSUE TITLE
Kubernetes: use automatically an allowlist for cluster.local domain

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#1526]
For example given that you have 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
spec:
  rules:
  - host: test-app.ingress.cluster.local
    http:
      paths:
      - backend:
          serviceName: test-app-service
          servicePort: main-port
```

I wan to have an allow list of IP CIDRs automatically enforced with `Source` or `SourceFromLast` predicates to separate internal routes from being called from public internet.

A default should add only private subnets to the allow list.
