### ISSUE TITLE
Non-matching requests are sent to route with Service of type ExternalName

### ISSUE THREAD

**Issue by wndhydrnt** [zalando/skipper#1553]
**Describe the bug**
When an Ingress points to a Service of type `ExternalName`, skipper creates a route that matches every host. Requests that do not match a host/path configuration of any other route are then sent to that route.

**To Reproduce**
Ingress and Service definitions:
```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-external-service
  annotations:
    kubernetes.io/ingress.class: skipper
  labels:
    app: my-external-service
spec:
  rules:
    - host: my-external-service.domain.local
      http:
        paths:
          - backend:
              serviceName: my-external-service
              servicePort: 443
---
kind: Service
apiVersion: v1
metadata:
  name: my-external-service
  labels:
    app: my-external-service
spec:
  type: ExternalName
  externalName: google.com
  ports:
    - port: 443
      name: https
      targetPort: 443
```

The resulting route:
```
kube_default__my_external_service______google_com: *
  -> setRequestHeader("Host", "google.com")
  -> "https://google.com:443";
```

**Expected behavior**

skipper only proxies requests to the host `my-external-service.domain.local` to `google.com`.

**Observed behavior**

skipper proxies all non-matching requests, e.g. `http://127.0.0.1:9090/foo` to `google.com`.
