### ISSUE TITLE
Support for https backend

### ISSUE THREAD

**Issue by tomekit** [zalando/skipper#1579]
I've configured Ingress with ALB using this: https://github.com/zalando-incubator/kube-ingress-aws-controller/tree/master/deploy

Given this rule for: `Ingress`
```
 http:
        paths:
          - path: /
            backend:
              serviceName: app-web
              servicePort: 443
```
and accessing my app over HTTPS using the: `https://mydomain.app-web.example.com`

my final Apache2 app receives HTTP traffic over 443 port which results in:
`100.96.4.10:443 100.96.5.0 - - [30/Oct/2020:16:43:04 +0000] "GET / HTTP/1.0" 400 0 "-" "-"`

> Bad Request
> 
> Your browser sent a request that this server could not understand.
> Reason: You're speaking plain HTTP to an SSL-enabled server port.
> Instead use the HTTPS scheme to access this URL, please.

Is there a way to enable secure backends, like it is possible with the NginX ingress with this:
```
annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
```
