### ISSUE TITLE
New Backend: S3 (with authorization)

### ISSUE THREAD

**Issue by ePaul** [zalando/skipper#1708]
**Is your feature request related to a problem? Please describe.**

When serving static files from an AWS S3 bucket via Skipper, currently the "Network" backend with a address like `https://<bucket>.s3.eu-central-1.amazonaws.com` is the straightforward way to go (and what is documented internally – I didn't find an example on the public Skipper docs). ~~This requires the bucket content to be publicly available to the internet (or at least to all AWS IPs in e.g. eu-central-1, which is almost as public)~~ _(this is not true, see [comment below](https://github.com/zalando/skipper/issues/1708#issuecomment-786218083))_.

**Describe the solution you would like**
There should be a way to use `s3://` URLs as backends, and authenticate with an AWS IAM role.
This way the bucket's permissions can be restricted to this role.

As suggested by @aermakov-zalando (in an internal chat), this could either be done by just proxying the GET requests, or by generating a short-term-signed URL which would be returned as a redirect URL.

I'm not sure whether this would be a separate backend type, or just a specialization of the Network backend.
The AWS IAM role to assume would need to be configured.

**Describe alternatives you've considered (optional)**
One could set up another proxy which takes requests from Skipper, optionally does some checks, adds the AWS IAM authorization information and forwards them to S3. This defeats the purpose of having the files in S3 in the first place (no need for a separate HTTP server deployment to deliver the static files).

**Additional context (optional)**

**Would you like to work on it?**
I currently have no Go skills nor knowledge of Skipper (besides reading part of the documentation), and also not much time. If I were the one to work on it, it would take a while until it got somewhere.

**Comment by AlexanderYastrebov** [comment]
> I'm not sure whether this would be a separate backend type, or just a specialization of the Network backend.

Alternative implementation might be an `s3` filter similar to https://github.com/zalando/skipper/blob/master/docs/reference/filters.md#static

**Comment by AlexanderYastrebov** [comment]
Also may be it would be possible to serve s3 via http and have special filter to provide AWS credentials.

**Comment by ePaul** [comment]
After I created this issue, we found out that this is not true:

> This requires the bucket content to be publicly available to the internet (or at least to all AWS IPs in e.g. eu-central-1, which is almost as public).

As part of the BucketPolicy, we can define that the read access is only possible for a certain virtual private cloud's network:

```yaml
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - ...
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}/*"
            Principal: "*"
            Condition:
              StringEquals:
                "aws:sourceVpc": "{{{VPC_ID}}}"
```

As VPC_ID, you need to use your accounts VPC ID. (In Zalando's deployment system, we have this as a variable which can be automatically injected.)

I still think the S3 access is useful (so I won't close this ticket), but my main use case doesn't require it anymore.
