### ISSUE TITLE
Readiness probe not working for skipper depoyment

### ISSUE THREAD

**Issue by aupadh12** [zalando/skipper#1743]
Hi Team,

I am trying to deploy skipper ingress in AWS EKS which already has nginx-ingress controller up and running.
But when I run the depployment.yaml, the readiness probe does not go through and container never really serves traffic.
Below is my deployment.yaml. Can someone please let me know where the issue is:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper-ingress
  namespace: kube-system
  labels:
    application: skipper-ingress
    version: v0.11.40
    component: ingress
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
  selector:
    matchLabels:
      application: skipper-ingress
  template:
    metadata:
      name: skipper-ingress
      labels:
        application: skipper-ingress
        version: v0.11.40
        component: ingress
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: skipper-ingress
      dnsPolicy: ClusterFirstWithHostNet
      #hostNetwork: true
      containers:
      - name: skipper-ingress
        image: awsrepo/skipper:v0.12.0
        ports:
        - name: ingress-port
          containerPort: 9999
          #hostPort: 9999
        - name: debug-port
          containerPort: 9992
        args:
          - "skipper"
          - "-kubernetes"
          - "-kubernetes-in-cluster"
          - "-kubernetes-path-mode=path-prefix"
          - "-kubernetes-https-redirect=false"
          - "-address=:9999"
          - "-wait-first-route-load"
          - "-proxy-preserve-host"
          - "-disable-metrics-compat"
          - "-debug-listener=:9922"
          - "-experimental-upgrade"
          - "-metrics-exp-decay-sample"
          - "-reverse-source-predicate"
          - "-lb-healthcheck-interval=3s"
          - "-access-log-json-enabled"
          - "-read-timeout-server=2m"
          - "-write-timeout-server=2m"
          - "-response-header-timeout-backend=2m"
          - "-timeout-backend=2m"
        readinessProbe:
          httpGet:
            path: /kube-system/healthz
            port: 9999
          initialDelaySeconds: 60
          timeoutSeconds: 5
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 999
```        

Please find the logs which I am receiving:
```
{"audit":"","duration":0,"flow-id":"","host":"100.64.66.211","level":"info","method":"GET","msg":"","proto":"HTTP/1.1","referer":"","requested-host":"100.64.32.41:9999","response-size":10,"status":404,"timestamp":"16/Mar/2021:10:58:44 +0000","uri":"/kube-system/healthz","user-agent":"kube-probe/1.17+"}
```
