### ISSUE TITLE
Skipper connection to back-end times out after 1 minute regardless of timeout settings

### ISSUE THREAD

**Issue by tomekit** [zalando/skipper#1748]
**Describe the bug**
My back-end takes more than a minute to respond. In fact I need to support up to 3600s request times. 
Skipper times out after 1m connection to back-end, regardless of timeout settings

```
[APP]time="2021-03-29T16:44:23Z" level=error msg="net.Error during backend roundtrip to http://100.103.181.103:80: timeout=true temporary=true: net/http: timeout awaiting response headers"
[APP]time="2021-03-29T16:44:23Z" level=error msg="error while proxying after 1m0.021587566s, route kube_default__app_ingress__demo_app_net_____app_web with backend network http://100.103.181.103:80, status code 504: dialing failed false: net/http: timeout awaiting response headers, remote host: xx.xx.xx.xx, request: \"POST /action HTTP/1.1\", user agent: \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0\""
```
I've decided to set all timeout settings to `0`:
```
- "-tls-timeout-backend=0"
- "-timeout-backend=0"
- "-read-header-timeout-server=0"
- "-write-timeout-server=0"
- "-idle-timeout-server=0"
- "-read-timeout-server=0"
```
unfortunately this doesn't affect the behavior of Skipper. It still fails after  `1m`. 

### To reproduce

**Run slow responding back-end**
index.php
```
<?php
sleep(65);
```
`php -S 127.0.0.1:8001`

**Run skipper:**
`skipper -inline-routes="hello: Path(\"/\") -> \"http://localhost:8001\"" -tls-timeout-backend=0 -timeout-backend=0 -read-header-timeout-server=0 -write-timeout-server=0 -idle-timeout-server=0 -read-timeout-server=0`

**Send request to Skipper**
`curl localhost:9090`
After 60s, you will receive: `Gateway Timeout` in your curl.

Skipper will display:
```
[APP]ERRO[0065] net.Error during backend roundtrip to http://localhost:8001: timeout=true temporary=true: net/http: timeout awaiting response headers 
[APP]ERRO[0065] error while proxying after 1m0.000938567s, route hello with backend network http://localhost:8001, status code 504: dialing failed false: net/http: timeout awaiting response headers, remote host: 127.0.0.1, request: "GET / HTTP/1.1", user agent: "curl/7.68.0" 
127.0.0.1 - - [29/Mar/2021:20:17:47 +0200] "GET / HTTP/1.1" 504 16 "-" "curl/7.68.0" 60000 localhost:9090 - -
```

**Expected behavior**
Timeout settings affect timeout values in practice.
**Observed behavior**
No practical change to timeout behavior.

YAML:
```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: skipper-ingress
  namespace: kube-system
  labels:
    component: ingress
spec:
  selector:
    matchLabels:
      component: ingress
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: skipper-ingress
      labels:
        component: ingress
        application: skipper
    spec:
      hostNetwork: true
      serviceAccountName: skipper-ingress
      containers:
        - name: skipper-ingress
          image: registry.opensource.zalan.do/pathfinder/skipper:latest
          ports:
            - name: ingress-port
              containerPort: 9999
              hostPort: 9999
            - name: metrics-port
              containerPort: 9911
          args:
            - "skipper"
            - "-kubernetes"
            - "-kubernetes-in-cluster"
            - "-address=:9999"
            - "-proxy-preserve-host"
            - "-serve-host-metrics"
            - "-enable-ratelimits"
            - "-experimental-upgrade"
            - "-metrics-exp-decay-sample"
            - "-lb-healthcheck-interval=3s"
            - "-metrics-flavour=codahale,prometheus"
            - "-enable-connection-metrics"
            - "-tls-timeout-backend=0"
            - "-timeout-backend=0"
            - "-read-header-timeout-server=0"
            - "-write-timeout-server=0"
            - "-idle-timeout-server=0"
            - "-read-timeout-server=0"
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          readinessProbe:
            httpGet:
              path: /kube-system/healthz
              port: 9999
            initialDelaySeconds: 5
            timeoutSeconds: 5

```
