### ISSUE TITLE
Error while processing filter oauthGrant - Skipper on AKS - Azure

### ISSUE THREAD

**Issue by tamer-abdulghani** [zalando/skipper#1752]
We have installed skipper on AKS on microsoft azure to be used as reverse proxy behind azure gateway. 
Currently, We are trying to configure authentication/authorization for skipper using OAuth2.0. However, we are getting some errors in the logs of Skipper thus we are unable to configure the Authorization step.

We have followed the steps below:

1.  Skipper configuration
```
          - "-enable-oauth2-grant-flow"
          - "-oauth2-access-token-header-name=App-Grant-Authorization"
          - "-oauth2-client-id=CLIENT_ID"
          - "-oauth2-client-secret=CLIENT_SECRET"
          - "-oauth2-secret-file=/path/to/secret"
          - "-oauth2-auth-url=https://login.microsoftonline.com/TENANT_ID/oauth2/authorize"
          - "-oauth2-token-url=https://login.microsoftonline.com/TENANT_ID/oauth2/token"
          - "-oauth2-tokeninfo-url=https://login.microsoftonline.com/TENANT_ID/.well-known/openid-configuration"
          - "-oauth2-callback-path=/oauth/callback"
``` 

2.  Skipper Ingress 
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "skipper-ingress"
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "default"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/request-timeout: 300
  labels:
    app: "skipper-ingress"
spec:
  rules:
    - host: "my.host.com"
      http:
        paths:
          - backend:
              serviceName: "skipper-ingress"
              servicePort: 80
```

3.  App Ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: skipper
    zalando.org/skipper-filter: oauthGrant() ->  modPath("^/my-service/", "/my-service/")
  name: my-service
  namespace: my-ns
spec:
  rules:
  - host: my.host.com
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 1234
        path: /my-service/*
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
```

So with these configuration:

- we're getting redirected successfully to Microsoft Azure Login 
- then we're logged in with our user/pass
- then redirected back to home page url which display normal JSON object
- Also we can find one cookie created with name "oauth2-grant" and other cookies for microsoft login

However, in Skipper logs we see these errors:
```
- error msg="error while processing filter during request: oauthGrant: interface conversion: interface {} is nil, not string ()"

- [APP]time="2021-04-07T13:54:35Z" level=error msg="error while proxying after 17.7µs, route _unknownroute_ with backend <unknown> <unknown>, status code 404: dialing failed false: route lookup failed, remote host: 10.42.104.73, request: \"GET /favicon.ico HTTP/1.1\", user
agent: \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36\""
{"audit":"","duration":0,"flow-id":"","host":"10.42.104.73:59778","level":"info","method":"GET","msg":"","proto":"HTTP/1.1","referer":"my.domain.com","requested-host":"my.domain.com","response-size":10,"status"
:404,"timestamp":"07/Apr/2021:13:54:35 +0000","uri":"/favicon.ico","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36"}
{"audit":"","duration":280,"flow-id":"","host":"10.42.104.73:59778","level":"info","method":"GET","msg":"","proto":"HTTP/1.1","referer":"","requested-host":"my.domain.com","response-size":0,"status":307,"timestamp":"07/Apr/2021:13:55:02 +0000","uri":"
/oauth/callback?code=0.ASEA1cvq5Fu7MIY2300CPODSCKJC0SYCJPoB4zMcYJfnohAAA.AQAIJFLKDSHFDoQ778UaB40ll6o
  
- [APP]time="2021-04-07T13:54:35Z" level=error msg="error while processing filter during request: oauthGrant: interface conversion: interface {} is nil, not string (goroutine 1767 [running]:\ngithub.com/zalando/skipper/proxy.tryCatch.func1(0xc0000177b0)\n\t/workspace/proxy
/proxy.go:718 +0xcf\npanic(0x107ca40, 0xc000324870)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/zalando/skipper/filters/auth.(*grantFilter).createTokenContainer(...)\n\t/workspace/filters/auth/grant.go:136\ngithub.com/zalando/skipper/filters/auth.(*grant
Filter).Request(0xc000441a40, 0x135ca98, 0xc00014c900)\n\t/workspace/filters/auth/grant.go:178 +0x832\ngithub.com/zalando/skipper/proxy.(*Proxy).applyFiltersToRequest.func1()\n\t/workspace/proxy/proxy.go:754 +0xcc\ngithub.com/zalando/skipper/proxy.tryCatch(0xc0005937d0,
0xc0005937b0)\n\t/workspace/proxy/proxy.go:726 +0x4f\ngithub.com/zalando/skipper/proxy.(*Proxy).applyFiltersToRequest(0xc0001dc000, 0xc0004c8840, 0x4, 0x4, 0xc00014c900, 0x0, 0x0, 0x0)\n\t/workspace/proxy/proxy.go:752 +0x336\ngithub.com/zalando/skipper/proxy.(*Proxy).do(
0xc0001dc000, 0xc00014c900, 0x0, 0x0)\n\t/workspace/proxy/proxy.go:1058 +0x2e5\ngithub.com/zalando/skipper/proxy.(*Proxy).ServeH)"

```

Any idea why are we getting these errors? or how can we check the user information ? or how can we verify if the token is validated successfully? and if tokeninfo-url is correct ?
