### ISSUE TITLE
Colons can't be escaped in path syntax

### ISSUE THREAD

**Issue by DestyNova** [zalando/skipper#1763]
## Describe the bug
Paths containing a literal colon can't be parsed literally and (apparently) fail to match.

## To reproduce
Example RouteGroup definition:
```yaml
    - path: /api/static/hello:world
      filters:
        - preserveHost("false")
        - setResponseHeader("Content-Type", "application/json")
        - 'inlineContent(`
          {
            "status": "Get to the choppa!"
          }
          `)'
```
2. Trying to call it:
```bash
curl -vH "Content-Type: application/json" \
	"$HOST/api/static/hello:world"
```

## Expected behavior
Response code 200 with JSON content as defined in the `inlineContent` example.

## Observed behavior
```
< HTTP/2 404
< date: Fri, 23 Apr 2021 14:20:04 GMT
< server: Skipper
<
{ [0 bytes data]
```

The same thing happens with both `path` and `pathSubtree`, probably because they're trying to parse `:world` as a placeholder for a path component. It probably expects to see those placeholders only preceded by a `/` rather than `hello`, so maybe that's why it won't match on the route I tried with curl.
I tried escaping the colon in the path expression with `%3a`, `%3A`, `\\:` and `\:`, none of which worked, and the last one seemed to cause a YAML parsing failure.

## Workaround
A colleague found that the `pathRegexp` filter treats the colon literally and presumably doesn't have path variable parsing, so we were able to use that to match successfully.

## Possible fixes
Escaping the colon could be a bit awkward since `\:` seemed to cause a problem parsing the manifest. I guess we could come up with a different special escape sequence, but nobody likes that.
We could also be more explicit about when a `:word` sequence is treated as a path variable placeholder -- it could be defined more strictly as only valid after a `/` path separator, and treated literally in all other cases. Or we could define it to be invalid in all other cases unless escaped, if we come up with a comfortable and intuitive way to escape them.
