### ISSUE TITLE
Custom route-level clusterClientRatelimit in Ingress

### ISSUE THREAD

**Issue by mortenbo** [zalando/skipper#1831]
Is there a way in the ingress file to define custom clusterClientRatelimit for specific routes? This is where I'm at atm:

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ourservice-{{deploy_env}}
  namespace: {{namespace}}
  labels:
    app: ourservice
    env: {{deploy_env}}
  annotations:
    kubernetes.io/ingress.class: skipper
    zalando.org/skipper-filter: lifo(10, 10, "10s") -> clusterClientRatelimit("ourservice-{{deploy_env}}", 10, "10s")
    zalando.org/skipper-routes: |
      a: Path("/login") -> clusterClientRatelimit("ourservice-login", 10, "10m") -> <loopback>;
      b: Path("/signup") -> clusterClientRatelimit("ourservice-login", 10, "10m") -> <loopback>;
spec:
  rules:
  - host: ourservice-{{deploy_env}}.{{cluster_name}}
    http:
      paths:
      - backend:
          serviceName: ourservice-{{deploy_env}}
          servicePort: 4000
```

The issue here seems to be that the rate limiter is *always on* for those two routes. It never relays the requests to our backend when not having made more than 10 reqs within 10 minutes.

I've tried `<loopback>`, `<dynamic>`, `http://127.0.0.1:4000`, and more. Either I'm just doing it plain wrong (it's been hard for me figuring this out via the docs or open-source code in GH) or ingress is not even made for this case.

I hope some can shed some light on this. Thank you!

**Comment by AlexanderYastrebov** [comment]
Hello.

To add ratelimit to the specific path/route you would either need _two_ ingress definitions for the _same_ backend and host, something like
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-login
  annotations:
    zalando.org/skipper-predicate: PathSubtree("/login")
    zalando.org/skipper-filter: clusterClientRatelimit("login-ratelimit", 1, "1m")
spec:
  rules:
  - host: app.example.org
    http:
      paths:
      - backend:
          serviceName: app-svc
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
spec:
  rules:
  - host: app.example.org
    http:
      paths:
      - backend:
          serviceName: app-svc
          servicePort: 80
```
or use [Routegroups](https://github.com/zalando/skipper/blob/master/docs/kubernetes/routegroups.md) to define routes explicitly which might be more user-friendly than several ingresses

> it's been hard for me figuring this out via the docs

This is something to improve for us in the docs, the closest thing is https://github.com/zalando/skipper/blob/master/docs/kubernetes/ingress-usage.md#ab-test
