### ISSUE TITLE
support for ingressClassName

### ISSUE THREAD

**Issue by aupadh12** [zalando/skipper#1976]
**Is your feature request related to a problem? Please describe.**
I am using skipper ingress version v0.13.188 as a proxy ingress controller which then forwards the traffic from my application to nginx ingress controller.
I have also recently upgraded the nginx ingress controller to 1.1.2.
I am noticing errors like below:
[APP]time="2022-03-09T09:50:14Z" level=error msg="error while proxying after 13.636284ms, route kube_kube_system__ngingx_to_skipper_ingress__shinyproxy_master_age_xyz_com_____skipper_ingress with backend
network http://100.64.234.65:9999/, status code 502: dialing failed true: failed to do backend roundtrip to 100.64.234.65:9999: dial tcp 100.64.234.65:9999: connect: cannot assign requested address, remote host: 100.64.144.195, request: "GET /favicon.ico HTTP/1.1", user agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36""

{"audit":"","duration":22,"flow-id":"","host":"100.64.144.195","level":"info","method":"GET","msg":"","proto":"HTTP/1.1","referer":"[https://shinyproxy-master-age.xyz.com/","requested-host":"shinyproxy-master-age.xyz.com","response-size":12,"status":502,"timestamp":"09/Mar/2022:09:50:14](https://shinyproxy-master-age.xyz.com/%22,%22requested-host%22:%22shinyproxy-master-age.xyz.com%22,%22response-size%22:12,%22status%22:502,%22timestamp%22:%2209/Mar/2022:09:50:14) +0000","uri":"/favicon.ico","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"}

As a result, I am getting 502 errors.
The skipper ingress was working completely fine on previous versions of ingress controller , i.e., 1.0.0.

**Describe the solution you would like**
o I was able to find the issue here.
In the ingress.yaml, we still need to use annotation --> kubernetes.io/ingress.class: "nginx"
I was using the latest syntax of -->
spec:
    ingressClassName: nginx

Please note that starting K8s 1.22, this annotation will be deprecated and will be removed.
So, I would like to suggest to create the syntax usable in skipper ingress.

**Would you like to work on it?**
Yes, but no time

**Comment by AlexanderYastrebov** [comment]
Related to #1892, see also https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/

> Please note that starting K8s 1.22, this annotation will be deprecated and will be removed.

While it is being deprecated I think it will continue to work as expected as it is an annotation and not e.g. a field that is removed.
The #1892 implemented ingress v1 support by copy-pasting the v1beta1 implementation so the question is should we remove v1beta1 support before doing changes to v1 ingress client.

**Comment by AlexanderYastrebov** [comment]
Interestingly there is a piece that actually checks `Spec.IngressClassName`
https://github.com/zalando/skipper/blob/2c79795de8f376d34e5b4fecdcc58718cd90aeb6/dataclients/kubernetes/clusterclient.go#L292-L295 

@aupadh12 do you set the `-kubernetes-ingress-v1`?

**Comment by aupadh12** [comment]
Hi,

I did not set the flag.
But I do know that:
Ingress API deprecation for extensions/v1beta1. As of Kubernetes 1.16 this API has been deprecated and is unavailable in 1.22. Teams that are using this API version and running 1.19 and above should migrate to the stable networking.k8s.io/v1 version.
	
Ingress Class Annotation deprecation - As of Kubernetes 1.18 the kubernetes.io/ingress.class annotation has been deprecated in favor of the ingressClassName. 

So, below is my ingress which is working for K8s version 1.21.5 but I dont think it will once we move to K8s 1.22.
However, if a ingress class is not set then default ingress class will be used which was set during the installation of ingress controller. So, in that case, the annotation will not work and we will have to use Spec.IngressClassName.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngingx-to-skipper-ingress
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 5000m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "420"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "420"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-body-size: 5000m
    nginx.ingress.kubernetes.io/affinity: cookie
    kubernetes.io/ingress.class: "nginx"
spec:
  #ingressClassName: nginx
  rules:
  - host: shinyproxy-master-age.xyz.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: skipper-ingress
            port:
              number: 9999
```

**Comment by aupadh12** [comment]
Also, currently my validation webhook for ingress controller skips all other ingress class name other than nginx.
This was fixed in nginx ingress controller 1.1.2.

**Comment by AlexanderYastrebov** [comment]
>> do you set the -kubernetes-ingress-v1 flag?
> I did not set the flag.

When flag is not set Skipper uses v1beta1 k8s API to get ingress definitions even if ingress was defined as v1.
This will stop working starting from 1.22 as it removes v1beta1 API, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
When flag is set, Skipper uses v1 API and should take `spec.ingressClassName` into account as far as I can tell from the code.

**Comment by aupadh12** [comment]
Hello @AlexanderYastrebov ,

I tried setting the flag in daemonset but I started receiving this error:
APP]time="2022-03-09T21:48:02Z" level=error msg="error while receiving initial data;failed to load cluster state: request failed, status: 403, 403 Forbidden"

Below is my daemonset file:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: skipper-ingress
  namespace: kube-system
  labels:
    application: skipper-ingress
    version: v0.13.188
    component: ingress
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      application: skipper-ingress
  template:
    metadata:
      name: skipper-ingress
      labels:
        application: skipper-ingress
        version:  v0.13.188
        component: ingress
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: skipper-ingress
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: skipper-ingress
        image: jaab-docker.artifactrepo.jnj.com/skipper:v0.13.188 
        ports:
        - name: ingress-port
          containerPort: 9999
          hostPort: 9999
        - name: metrics-port
          containerPort: 9911
        - name: debug-port
          containerPort: 9992
        #env:
          #- name: KUBE_NAMESPACE
             #valueFrom:
                #fieldRef:
                   #fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 150m
            memory: 256Mi
        args:
          - "skipper"
          - "-kubernetes"
          - "-kubernetes-in-cluster"
          - "-kubernetes-ingress-v1"
          - "-kubernetes-path-mode=path-prefix"
          - "-kubernetes-https-redirect=false"
          - "-address=:9999"
          - "-wait-first-route-load"
          - "-proxy-preserve-host"
          - "-disable-metrics-compat"
          - "-debug-listener=:9922"
          - "-experimental-upgrade"
          - "-metrics-exp-decay-sample"
          - "-reverse-source-predicate"
          - "-lb-healthcheck-interval=3s"
          - "-access-log-json-enabled"
          - "-read-timeout-server=5m"
          - "-write-timeout-server=5m"
          - "-response-header-timeout-backend=5m"
          - "-timeout-backend=5m"
          - "-whitelisted-healthcheck-cidr=10.0.0.0/25"
        readinessProbe:
          httpGet:
            path: /kube-system/healthz
            port: 9999
          initialDelaySeconds: 30
          timeoutSeconds: 5
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
      imagePullSecrets:
      - name: secret-docker
```
