### ISSUE TITLE
Ability to specify the Kubernetes namespace in the service backend to lookup the target service backend

### ISSUE THREAD

**Issue by lukibahr** [zalando/skipper#2187]
**Is your feature request related to a problem? Please describe.**

Im uncertain if this feature request is bug, or intended behaviour, but we want to specify the namespace in the backends section of a routegroup of type service (kubernetes service), to lookup the service for. If we deploy the RouteGroup object in the same namespace, where the service, we want to route to is located, the routing works, but atm. I'm deploying all 
RouteGroup objects in the same namespace where skipper pods live in.

We're deploying all RouteGroup objects in the same namespace, as the skipper pods are deployed to, in this case `skipper`. 

```
apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
  annotations:
    zalando.org/routegroup.class: internal
  name: example
  namespace: skipper # the routegroup is created in namespace, where the skipper pods are running.
spec:
  backends:
  - name: prometheus
    serviceName: monitoring-prometheus # here we want to define the services namespace, to route to, e.g. cattle-monitoring-system/monitoring-prometheus where cattle-monitoring-system is the service
    servicePort: 9090
    type: service
  hosts:
  - example.domain.com
  routes:
  - backends:
    - backendName: prometheus
    filters:
    # any filters welcome
    - setPath("/")
    pathSubtree: /
[... lines omitted ...]
```

which results in the follwing error message: 

```
skipper-ingress-644bbcd8f8-ngx8f skipper-ingress {"level":"error","msg":"[routegroup] error transforming external hosts for skipper/example: service not found: skipper/monitoring-prometheus.","time":"2023-01-05T13:37:30Z"}
```

The `skipper/` prefix which indicates the namespace to search the service for, comes from the RouteGroup objects metadata.namespace field, as defined in the code here: https://github.com/zalando/skipper/blob/master/dataclients/kubernetes/routegroup.go#L610.

Am I missing something, or is it possible to specify the namespace to search the service for? 

**Describe the solution you would like**

We would like to be able to specify the namespace in the RouteGroup object, where the service to be routed to lives in:

````
apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
  annotations:
    zalando.org/routegroup.class: internal
  name: example
  namespace: skipper # the routegroup is created in namespace, where the skipper pods are running.
spec:
  backends:
  - name: prometheus
    serviceName: cattle-monitoring-system/monitoring-prometheus # notation like svc/service-name
    servicePort: 9090
    type: service
  hosts:
[... lines omitted ...]
````

**Describe alternatives you've considered (optional)**
The alternative would be deploying the RouteGroup objects in the namespace, where the service to be routed to lives in. If this is intended and expected behaviour, please let me know.

**Would you like to work on it?**
No, but able to test improvements / new features.
