### ISSUE TITLE
RouteGroup traffic switching should take care about internal routing details

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#2268]
**Is your feature request related to a problem? Please describe.**

As of today, you can specify `weight` in the [backendReference object](https://opensource.zalando.com/skipper/kubernetes/routegroup-crd/#backend-reference), but this can lead to wrong routing behavior, because of [route matching](https://opensource.zalando.com/skipper/tutorials/basics/#route-matching).
Example:

```
apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
spec:
  defaultBackends:
  - backendName: v1
    weight: 90
  - backendName: v2
    weight: 10
  routes:
  - pathSubtree: /
  - pathSubtree: /
    predicates:
    - Cookie("foo", "^")
``` 
This routegroup will be translated to eskip in skipper:
```
v1_r1: PathSubtree("/") && Traffic(0.9) -> ... -> <backend1>
v2_r1: PathSubtree("/") -> ... -> <backend2>
v1_r2: PathSubtree("/") && Cookie("foo", "^")  && Traffic(0.9) -> ... -> <backend1>
v2_r2: PathSubtree("/") && Cookie("foo", "^")  -> ... -> <backend2>
```
or
```
v1_r1: PathSubtree("/") -> ..
v2_r1: PathSubtree("/") && Traffic(0.1) -> ..
v1_r2: PathSubtree("/") && Cookie("foo", "^")  -> ..
v2_r2: PathSubtree("/") && Cookie("foo", "^")  && Traffic(0.1) -> ..
```
In the first case v1_r1 and v2_r2 have the same weights, such that traffic split is not 90/10 but closer to 50/50 (or even 45/55)
In the second case v2_r1 and v1_r2 have the same weights, such that traffic split is not persisted based on cookie at 10% chance. 

**Describe the solution you would like**

Skipper should internally understand the route weights and balance the weights such that the intended behavior would happen.
To resolve the routing issue, the routes for the example above should be: 
```
v1_r1: PathSubtree("/") && Traffic(0.9) -> ..
v2_r1: PathSubtree("/") -> ..
v1_r2: PathSubtree("/") && Cookie("foo", "^")  && True() && Traffic(0.9) -> ..
v2_r2: PathSubtree("/") && Cookie("foo", "^") && True() -> ..
```
or
```
v1_r1: PathSubtree("/") -> ..
v2_r1: PathSubtree("/") && Traffic(0.1) -> ..
v1_r2: PathSubtree("/") && Cookie("foo", "^") && True() -> ..
v2_r2: PathSubtree("/") && Cookie("foo", "^")  && True() Traffic(0.1) -> ..
```
