### ISSUE TITLE
Unable to run Skipper on K8s v1.27

### ISSUE THREAD

**Issue by vcozzolino** [zalando/skipper#2357]
**Describe the bug**
Following the instructions found at this link https://opensource.zalando.com/skipper/kubernetes/ingress-controller/ do not lead to successfully deploying the Skipper ingress controller on Kubernetes version 1.27. The Skipper binary generated with `make build` works when launched from a shell.

```
root@xxx-k8s-dev:~/skipper# k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.2
```

**To Reproduce**
1. Clone this repo
2. Run `kubectl create -f docs/kubernetes/deploy/daemonset`

**Expected behavior**

Skipper YAML files created correctly and ingress-controller pods are running.

**Observed behavior**

Running `kubectl create -f docs/kubernetes/deploy/daemonset` already generates an error due to the deprecation of `PodSecurityPolicy` as of version v1.25 of Kubernetes (https://kubernetes.io/docs/reference/using-api/deprecation-guide/#psp-v125):
```
resource mapping not found for name: "hostnetwork" namespace: "kube-system" from "docs/kubernetes/deploy/daemonset/rbac.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

On top of that, Skipper fails to run and generates the following output:

```
root@xxx-k8s-dev:~/skipper# k logs -f -n kube-system skipper-ingress-v9qr2
[APP]time="2023-05-31T08:59:07Z" level=info msg="Expose metrics in all format"
[APP]time="2023-05-31T08:59:07Z" level=info msg="register sigterm handler"
[APP]time="2023-05-31T08:59:07Z" level=info msg="Updated secret file: /var/run/secrets/kubernetes.io/serviceaccount/token"
[APP]time="2023-05-31T08:59:07Z" level=info msg="enabled ratelimiters true: []"
[APP]time="2023-05-31T08:59:07Z" level=info msg="support listener on :9911"
[APP]time="2023-05-31T08:59:07Z" level=info msg="Run secrets path refresher every 1m0s, but update once first"
[APP]time="2023-05-31T08:59:07Z" level=info msg="Updated secret file: /var/run/secrets/kubernetes.io/serviceaccount/token"
[APP]time="2023-05-31T08:59:07Z" level=error msg="error while receiveing initial data;failed to load cluster state: resource not found"
[APP]time="2023-05-31T08:59:10Z" level=error msg="error while receiveing initial data;failed to load cluster state: resource not found"
[APP]time="2023-05-31T08:59:13Z" level=error msg="error while receiveing initial data;failed to load cluster state: resource not found"
[APP]time="2023-05-31T08:59:16Z" level=error msg="error while receiveing initial data;failed to load cluster state: resource not found"
[APP]time="2023-05-31T08:59:19Z" level=error msg="error while receiveing initial data;failed to load cluster state: resource not found"
[APP]time="2023-05-31T08:59:22Z" level=error msg="error while receiveing initial data;failed to load cluster state: resource not found"
[APP]time="2023-05-31T08:59:25Z" level=error msg="error while receiveing initial data;failed to load cluster state: resource not found"
```

**Comment by AlexanderYastrebov** [comment]
What is the skipper version you run?
Please use one of the recent version from https://github.com/zalando/skipper/releases

**Comment by szuecs** [comment]
@vcozzolino can you try to drop the psp definition from `docs/kubernetes/deploy/daemonset/rbac.yaml`?

Here what I would guess you need to have in rbac.yaml:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skipper-ingress
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skipper-ingress
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
- apiGroups: [""]
  resources:
    - namespaces
    - services
    - endpoints
    - pods
  verbs:
    - get
    - list
- apiGroups:
  - zalando.org
  resources:
  - routegroups
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skipper-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skipper-ingress
subjects:
- kind: ServiceAccount
  name: skipper-ingress
  namespace: kube-system
```
