### ISSUE TITLE
Failing Ingress path after updating to latest Skipper version

### ISSUE THREAD

**Issue by janavenkat** [zalando/skipper#2746]
**Describe the bug**

Currently we're trying to update from version `v0.13.90` to latest `v0.18.51` and we did updated our RBAC as well for ingress. 

After updating to latest version in logs we noticed the error's

```
[APP]time="2023-11-22T13:25:33Z" level=info msg="route settings received"
[APP]time="2023-11-22T13:25:33Z" level=info msg="route settings applied"
[APP]time="2023-11-22T13:25:33Z" level=error msg="* or : in middle of path component .*)?$"
[APP]time="2023-11-22T13:25:33Z" level=error msg="* or : in middle of path component .*)?$/**"
[APP]time="2023-11-22T13:25:33Z" level=error msg="* or : in middle of path component .*)?$/"
```

**To Reproduce**
Am using Kubernetes, in [Ingress definition](https://github.com/zalando/skipper/blob/f16758f090bc207fb05b88d0a3ff7c26eaa7c999/docs/kubernetes/ingress-usage.md) we use `pathType: Prefix` and skipper uses ` PathSubtree` predicate. 

My example ingress look like this:
```
apiVersion: networking.k8s.io/v1  
kind: Ingress  
metadata:  
  namespace: default  
  name: test-ingresss
spec:  
  rules:  
  - host: example.com
    http:  
      paths:  
      - path: "/(testpath)(/.*)?$"
         pathType: Prefix
```
and we do have other regex example `/(hello/testpaths/anotherpath)(/.*)?$` So we're started getting this error `* or : in middle of path component .*)?$` from here https://github.com/zalando/skipper/blob/f16758f090bc207fb05b88d0a3ff7c26eaa7c999/pathmux/tree.go#L120

**Expected behavior**

No error's about path

**Observed behavior**
```

[APP]time="2023-11-22T13:25:33Z" level=info msg="route settings received"
[APP]time="2023-11-22T13:25:33Z" level=info msg="route settings applied"
[APP]time="2023-11-22T13:25:33Z" level=error msg="* or : in middle of path component .*)?$"
[APP]time="2023-11-22T13:25:33Z" level=error msg="* or : in middle of path component .*)?$/**"
[APP]time="2023-11-22T13:25:33Z" level=error msg="* or : in middle of path component .*)?$/"
```
