### ISSUE TITLE
Kubernetes Ingress: Weighted Traffic Switching

### ISSUE THREAD

**Issue by hjacobs** [zalando/skipper#324]
Use the new traffic functionality (introduced with #319) to support weighted traffic switching for Kubernetes Ingress. This enables green/blue or canary deployments.

Idea: use different backends (services) in the Ingress and use relative weights to specify how much traffic each backend service should receive. The relative weights are annotated as a simple JSON object (backend service name -> relative weight).

Relative weights can be specified as arbitrary float values, examples for expressing exactly the same traffic distribution (20% to 80%):

*  {"my-app-green": 0.2, "my-app-blue": 0.8}
*  {"my-app-green": 2, "my-app-blue": 8}
*  {"my-app-green": 20, "my-app-blue": 80}
*  {"my-app-green": 1, "my-app-blue": 4}

Example `ingress.yaml` for switching 10% of the traffic to the new service `my-app-v2`.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    zalando.org/backend-weights: |
      {"my-app-v1": 90, "my-app-v2": 10}
  name: my-app
spec:
  rules:
  - host: my-app.example.org
    http:
      paths:
      - backend:
          serviceName: my-app-v1
          servicePort: 80
      - backend:
          serviceName: my-app-v2
          servicePort: 80
      - path: /some-sub-path-without-traffic-switching
        backend:
          serviceName: some-other-app
          servicePort: 80
```

Benefits:

* Simplicity: we only annotate the Ingress resource with the weights (if we could extend Ingress we would put the weight into the `backend` property as proposed in https://github.com/kubernetes/kubernetes/issues/25485)
* Usability: the traffic weights are easily understandable by humans and by using relative weights it's hard to make some error (nobody needs to make sure that the sum is exactly 1.0 or 100).

Drawbacks:

* Would need to be extended if we would need to support traffic switching on all levels with the same backends (i.e. differents paths routing to the same service) --- I consider it unlikely that we need this
* The Ingress resource needs to be changed (overwritten) for switching traffic --- this can be approached by using templating in the CD pipeline and/or extracting the weights to a different resource in the future (TPR, config map?)
