### ISSUE TITLE
tlsPassClientCertificates() filter not working in kubernetes 

### ISSUE THREAD

**Issue by rickhlx** [zalando/skipper#3280]
**Describe the bug**
Client TLS certificates are not being passed through to the `X-Forwarded-Tls-Client-Cert` header when running Skipper for ingress in Kubernetes.

**To Reproduce**
1. Skipper CLI args:
```
skipper --kubernetes -address=:8443 -kubernetes-enable-tls
```

2. Ingress definition with TLS secret termination and `tlsPassClientCertificates()`
```yaml
apiVersion: networking.k8s.io/v1                                                                                                       
kind: Ingress                                                                                                                          
metadata:                                                                                                                              
  annotations:                                                                                                                                                                                   
    zalando.org/skipper-filter: tlsPassClientCertificates() -> logHeader("request" , "response")                                                                                                                                                                                                                                                                                                                                                                                            
  name: foobar
  namespace: foobar
spec:                                                                                                                                  
  rules:                                                                                                                               
  - host: foobar.com
    http:                                                                                                                              
      paths:                                                                                                                           
      - backend:                                                                                                                       
          service:                                                                                                                     
            name: foobar
            port:                                                                                                                      
              name: web                                                                                                                
        path: /foo
        pathType: Prefix                                                                                                               
  tls:                                                                                                                                 
  - hosts:                                                                                                                             
    - foobar.com
    secretName: foo-tls
status:                                                                                                                                
  loadBalancer: {}   
```

3. Request

```
curl -X POST https://foobar.com/foo/bar--cert cert.crt --key cert.key
```

**Expected behavior**

The pod running the foobar application should receive the `X-Forwarded-Tls-Client-Cert` from Skipper and should be logged by skipper when using the `logHeader()` filter

**Observed behavior**

The pod running the application does not get the `X-Forwarded-Tls-Client-Cert` header with the encoded certificate.

```
Host: foobar.com
Accept: */*
Content-Length: 79
Content-Type: application/x-www-form-urlencoded
User-Agent: curl/7.81.0
```
