### ISSUE TITLE
Kubernetes service ExternalName should be possible to target from ingress

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#549]
As a user, I want to specify an external proxy target within the ingress object.

In Kubernetes this could be done with [service type ExternalName](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services---service-types), but the skipper kubernetes dataclient does not support this, yet.

**Comment by daviddyball** [comment]
Hey @szuecs, did you ever find a way around this? We're running Skipper and I want to do exactly this, but I'm getting `error during backend roundtrip: kube xxxxxxxxxxxxxxxx service: dial tcp :443: getsockopt: connection refused`

**Comment by daviddyball** [comment]
Ahhh right, this bypasses my need to use `ExternalName` completely 😛 

Currently I have this (with your additions):

```
apiVersion: v1
kind: Service
metadata:
  name: logs
spec:
  type: ExternalName
  externalName: logs.internal
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: logs
  annotations:
    kubernetes.io/ingress.class: skipper
    zalando.org/skipper-routes: |
      Host("logs.example.com") -> "https://logs.internal";
spec:
  rules:
  - host: logs.example.com
    http:
      paths:
      - backend:
          serviceName: logs
          servicePort: https
```

When I apply it I get this in the skipper logs:
```
[APP]time="2018-05-17T10:14:29Z" level=info msg="route settings, update, route: kube_default__logs__logs_example_com____logs: Host(/^logs[.]example[.]com$/) -> \"http://:443\""

And this is what I get when I try to access:
```
[APP]time="2018-05-17T10:15:28Z" level=error msg="error during backend roundtrip: kube_default__logs__logs_example_com____logs: dial tcp :443: getsockopt: connection refused"
[APP]time="2018-05-17T10:15:28Z" level=error msg="error while proxying, route kube_default__logs__logs_example_com____logs, status code 503: dial tcp :443: getsockopt: connection refused"
81.139.52.202 - - [17/May/2018:10:15:28 +0000] "GET /_plugin/kibana/ HTTP/1.1" 503 20 "" "curl/7.59.0" 0 logs.example.com
```

Any ideas?

**Comment by daviddyball** [comment]
There's no option to ignore certificate validation errors?

**Comment by szuecs** [comment]
`-insecure` :)

**Comment by daviddyball** [comment]
ahhh right... all of our certificate validation happens on the ELB's in AWS, so I'm not too worried about 
SSL validation for proxy traffic. I'll try with that and see how I get on.

Thank you for your help. I really appreciate it 👍

**Comment by daviddyball** [comment]
Hi @szuecs I've applied `-insecure` and it doesn't appear to be an SSL issue. I think the issue might be that there is no destination being set on the route that gets created.

The logs are showing `status code 503: dial tcp :443: getsockopt: connection refused`... but shouldn't it be `dial tcp <address>:443:`?

**Comment by szuecs** [comment]
Can you exec into the skipper pod and list all routes:

    wget -O/dev/stdout localhost:9911/routes

**Comment by daviddyball** [comment]
Sure here's the output

```
kube_default__logs__logs_example_com____logs: Host(/^logs[.]example[.]com$/)
  -> "http://:443";
```

There were a few others relating to services on-cluster, but I cut them out.

**Comment by szuecs** [comment]
@daviddyball Can you post an updated version of your current ingress object?

**Comment by szuecs** [comment]
@daviddyball can you please change the port in the routes annotation to 444, to see what skipper shows in the routing table (`wget -O/dev/stdout localhost:9911/routes` )?
It looks really strange and please also check that you did not replace some names in a wrong way. The k8s object to the route looks strange to me.

**Comment by daviddyball** [comment]
Using this config

```
apiVersion: v1
kind: Service
metadata:
  name: logs
  namespace: operations
spec:
  type: ExternalName
  externalName: logs.internal
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: logs
  namespace: operations
  annotations:
    kubernetes.io/ingress.class: admin
    zalando.org/skipper-routes: |
      Host("logs.example.com") -> "https://logs.internal:443"
spec:
  rules:
  - host: logs.example.com
    http:
      paths:
      - backend:
          serviceName: logs
          servicePort: 444
```


I get this route

```
kube_operations__logs__logs_example_com____logs: Host(/^logs[.]example[.]com$/)
  -> "http://:443";
```
