### ISSUE TITLE
skipper route CRD

### ISSUE THREAD

**Issue by vetinari** [zalando/skipper#660]
We're currently running skoap with a single route like this
```
   Path("/*") && Method("GET")
              -> auth("/services")
              -> dropRequestHeader("Authorization")
              -> basicAuth("username", "secret")
              -> "https://special.service.example.com";
```
with `auth("/services")` -> `oauthTokeninfoAllKV("realm","/services")` for newer skipper versions.

We would now need an ingress definition with incoming host names defined and one disconnected kubernetes service, that is not deleted in later and has a special meaning for this route. We have no pods involved in this route. The current `zalando.org/skipper-routes` annotation can be used as workaround, but needs to have a kubernetes service that exists, too.
https://github.com/zalando/skipper/issues/512

**Comment by szuecs** [comment]
We might want to think about having a customer skipper route CRD for the use case of custom skipper routes.

**Comment by szuecs** [comment]
Request for comments:

```
apiVersion: zalando.org/v1
kind: SkipperRoute
metadata:
  name: "{{{APPLICATION}}}-blogposts-put"
  labels:
    application: "{{{APPLICATION}}}"
    version: "{{{BUILD_VERSION}}}"
spec:
  ingress: "name-reference"  # optional, copy base predicates and filters from ingress
  filters: # optional
  - localRatelimit(“1m”, 10)
  - enableAccessLog()
  - flowId("reuse")
  predicates:
  - JWTPayloadAllKV("iss", "https://idp.example.com", “https://identity.example.com/role”, “publisher”)
  - Method(“PUT")
  - PathSubtree(“/blogposts/:id”)
status:
  applied: <timestamp>
```

My Questions:
- [ ] How should the behavior of the `status` field be?
  - first applied?
  - should all instances add themselves, but how to delete them again?
  - does it makes sense to have a status or do we need some other data?
- [ ] Anything you miss in this CRD to support your use cases?

**Comment by szuecs** [comment]
@aermakov-zalando do you have ideas for the status field, because you talked about "the usual pattern is that the controller writes the latest value from metadata.generation into status.observedGeneration when it does stuff". One problem is that we have N skippers and only one object status field, but maybe you have an idea.

**Comment by aermakov-zalando** [comment]
No idea. I'd either create a separate controller that would get the results from all Skipper instances and update the status, or use leader election in Skippers and collect the data in one of the instances. Both of these would be annoying to implement, though.

**Comment by aermakov-zalando** [comment]
A couple of suggestions:
 * Use a list of routes instead of just one. This will simplify managing more complicated overrides.
 * Add the hostname explicitly and make it required. Right now it's very easy to accidentally screw up everything running in the cluster.

**Comment by szuecs** [comment]
We think about creating a RouteGroup CRD that can be traffic switched as a set of routes with https://github.com/zalando-incubator/stackset-controller

**Comment by szuecs** [comment]
We started to work on the skipper RouteGroup CRD. Some example yaml files you can see in https://github.com/zalando/skipper/tree/feature/routegroup-crd/dataclients/kubernetes/fixtures

Why:
- more DRY object than ingress (hosts and backends separated from path rules)
- enable skipper specific features
- we don't want to have an object with multiple hostnames that have different backends 
- orchestrate traffic switching for a full RouteGroup

## Examples
### Minimal example
```
apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
  name: my-routes
spec:
  hosts:
  - foo.example.org
  backends:
  - serviceName: foo-service
    servicePort: 80
  paths:
  - path: /
```

### route + redirect route
One example case that happens more often is only possible with more than 1 ingress: ingress + redirect:
```
apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
  name: my-routes
spec:
  backends:
  - serviceName: foo-service
    servicePort: 80
  paths:
  - path: /login
    method: get
    configs:
    - filters:
      - redirectTo(301, "https://login.example.org")
  - path: /
```

### complex routes
```
apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
  name: my-routes
spec:
  hosts:
  - www.complex.example.org
  - complex.example.org
  backends:
  - serviceName: foo-service-v1
    servicePort: 80
  paths:
  - path: /api/resource
    method: post
    configs:
    - filters:
      - ratelimit(20, "1m")
      - oauthTokeninfoAllKV("iss", "https://accounts.google.com", "email", "skipper-router@googlegroups.com")
      predicates:
      - JWTPayloadAllKV("iss", "https://accounts.google.com", "email", "skipper-router@googlegroups.com")
  - path: /api/resource/*
    method:  get
    configs:
    - filters:
      - clientRatelimit(100, "1m", "Authorization")
      - oauthTokeninfoAllScope("read.resource", "list.resource")
```

### Traffic switching case
```
apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
  name: my-routes
  annotations:
    zalando.org/backend-weights:
      {"foo-service-v1": 80, "foo-service-v2": 20}
spec:
  backends:
  - serviceName: foo-service-v1
    servicePort: 80
  - serviceName: foo-service-v2
    servicePort: 80
  paths:
  - path: /api/resource
    method: post
    configs:
    - filters:
      - ratelimit(20, "1m")
      - oauthTokeninfoAllKV("iss", "https://accounts.google.com", "email", "skipper-router@googlegroups.com")
      predicates:
      - JWTPayloadAllKV("iss", "https://accounts.google.com", "email", "skipper-router@googlegroups.com")
  - path: /api/resource/*
    method:  get
```

### A/B test
```
apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
  name: my-routes
spec:
  backends:
  - serviceName: service-b
    servicePort: 80
  paths:
  - path: /
    config:
    - filters:
      - responseCookie("canary", "A")
      predicates:
      - Traffic(.1)
    backends:
    - serviceName: service-a
      servicePort: 80
  - path: /
    config:
    - filters:
      - responseCookie("canary", "B")
  - path: /
    config:
    - predicates:
      - Cookie("canary", "team-foo")
  - path: /
    config:
    - predicates:
      - Cookie("canary", "A")
    backends:
    - serviceName: service-a
      servicePort: 80
  - path: /
    config:
    - predicates:
      - Cookie("canary", "B")
```

**Comment by aermakov-zalando** [comment]
Looks very nice! A couple of suggestions/questions:
 * Move `filters`/`predicates` into the path object. They also probably shouldn't be an array, unless I'm missing a use case?
 * Traffic switching: make it a first class field (either in `spec` or in `status`). It's a new resource anyway, no need to have it as a weird annotation.
 * How would custom destination work in this case (`<shunt>`, or a URL)? Maybe worth adding a `destination` key, with several options, e.g.

       destination:
         shunt: True

       destination:
         url: https://foo.zalan.do

       destination:
         backends:
           - serviceName: service-a
             servicePort: 80

**Comment by aryszka** [comment]
for destination: let's use a backend type enumeration, shunt/loopback/network/service, where service is the default and resolves to the LB endpoints.

**Comment by szuecs** [comment]
@aermakov-zalando The config key is used to have filters+predicates as a list of configs, which is an internal use case with fabric.

The problem we discussed with the traffic switching is that we have multiple controllers writing this object and if we have the annotation it's more safe (IIRC) to change from stackset controller the traffic settings. The problem with status is that it should reflect the current state not the goal.

The destinations I don't fully understand now with @aryszka's addition. Do you mean
```
destination:
  backend_type: <shunt>
  backends:
    - serviceName: service-a
      servicePort: 80
```

Additional questions: Would we ignore `backends`, if we have a `backend_type`?

**Comment by aermakov-zalando** [comment]
@szuecs Could you describe the use case, or how this would be used in practice? I still don't understand why an extra key is necessary.

Having traffic weights in the `spec` is perfectly fine, having it in the annotation doesn't really get you any extra safety.

**Comment by aryszka** [comment]
@szuecs yes, something like that.

the possible types could be: shunt, loopback, service (default), external

shunt would not require further fields, loopback neither. Service would be the default, but it would require the fields as you described above. The external would mean any free URL address (without path).

**Comment by aryszka** [comment]
see the above suggestion for defining the variants of a single destination. As we discussed since then, we will probably have to support multiple destinations for the traffic switching.

**Comment by mikkeloscar** [comment]
@aermakov-zalando 

> Having traffic weights in the spec is perfectly fine, having it in the annotation doesn't really get you any extra safety.

The only point against the spec would be if we want to support re-applying the `RouteGroup` without overwriting the traffic state. This would not be needed in a stackset case if we store the desired/actual traffic somewhere other than the RouteGroup.

**Comment by aermakov-zalando** [comment]
@mikkeloscar `apply` shouldn't touch any keys that it didn't provision, so I don't think it'll be an issue.

**Comment by hjacobs** [comment]
Can we have some design proposal document (Markdown file in this repo?) to have a nice overview on how it will look like? It's really hard for me to follow this comment thread as I was not involved from the start.

**Comment by aryszka** [comment]
@hjacobs good idea, creating one. Just one last comment, to jot down what we just discussed IRL. The traffic weights, could also be part of the destination entries, s.g. like:

```
destinations:
  - type: service
    serviceName: service-a-1
    port: 80
  - type: service
    serviceName: service-a-2
    port: 80
    weight: 0.2
```
