### ISSUE TITLE
Nondeterministic route matching ?

### ISSUE THREAD

**Issue by beenokle** [zalando/skipper#662]
I have an ingress. Lets say this simplified:
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
spec:
  rules:     
  - host: "myhost.com"
    http:
      paths:
      - path: "/path"
         backend:
          serviceName: upstream1
          servicePort: 80
      - backend:
          serviceName: upstream2
          servicePort: 80
```

I have three nodes in cluster.
When I run `curl -H "host: myhost.com" localhost:9999/path/foo/bar/long/path/1` locally on each node I got different results, for instance two times expected result from `upstream1`, and on another node I got unexpected result from `upstream2`
But If I do the same request directly to clusterIP of the service , I got expected result on each node. This narrows down the source of my issue to Skipper. 

Version is `0.10.13`

**Comment by hjacobs** [comment]
This looks like a bug, but can you first check whether skipper correctly updated all routes on both nodes?  I could suspect that one skipper instance (on of the nodes) has outdated routes.

**Comment by szuecs** [comment]
Hi!

We had a similar case yesterday. The current workaround is to use 2 ingress and to specify also a Predicate annotation on the path ingress.   

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress-path
  annotations:
    zalando.org/skipper-predicate: PathSubtree("/path")
spec:
  rules:     
  - host: "myhost.com"
    http:
      paths:
      - path: "/path"
         backend:
          serviceName: upstream1
          servicePort: 80
```

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress-root
  annotations:
spec:
  rules:     
  - host: "myhost.com"
    http:
      paths:
      - backend:
          serviceName: upstream2
          servicePort: 80
```
