### ISSUE TITLE
https for Kubernetes backends

### ISSUE THREAD

**Issue by aryszka** [zalando/skipper#683]
Consider supporting https in routes generated for Kubernetes.

Questions:

- how should the ingress spec indicate this?
- Skipper is not a TLS proxy, can this be misleading if someone expects end-to-end encryption?

**Comment by hjacobs** [comment]
I don't understand, what do you want to achieve? What does "https" for Kubernetes backends mean?

**Comment by aryszka** [comment]
@hjacobs I tried to rephrase the content of the issue. What I meant was that a service in the cluster listens accepts requests via https instead of http.

**Comment by szuecs** [comment]
So you mean to use sni to identify the target or how do you think it should work?
Can you elaborate more on how a user would use this feature?

**Comment by aryszka** [comment]
I don't know how we could identify these targets.

The use case I can imagine is that a user wants to run a service only over HTTPS even inside the cluster, but also wants to make it accessible for the world outside the cluster, so wants to create an ingress for it.

**Comment by szuecs** [comment]
This use case is covered by service type loadbalancer, use plain tcp.
If you want to support it with ingress we would need to do the route decision based on SNI. We have to understand how to get the data from the transport to make this decision and we need to have a lower layer predicate which isn’t based on http.Request . It would be nice to have it and can enable a lot of use cases that you are not aware of. For example manual access to databases.

**Comment by mikkeloscar** [comment]
@szuecs @aryszka I don't think you are talking about the same thing :)

As I understand @aryszka (correct me if I'm wrong) you want to support the case where you have an application configured like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    application: myapp
spec:
  selector:
    matchLabels:
      application: myapp
  template:
    metadata:
      labels:
        application: myapp
    spec:
      containers:
      - name: myapp
        image: myapp:latest
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: "myapp"
  name: "myapp"
spec:
  selector:
    application: "myapp"
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "myapp"
spec:
  rules:
    - host: "myapp.example.org"
      http:
        paths:
          - backend:
              serviceName: "myapp"
              servicePort: 443
```

And the skipper endpoints should be configured to be `https://10.2.1.1` or something like that?

The biggest challenge for supporting this IMO, is how do you handle certificates? you would need to tell skipper which CA to use and make sure the pods have the pod IP in their certificate. This could be simplified a bit by only using the service endpoint for HTTPS backends as you can share the predictable service name for all the pods. The downside is you would loose the load balancing feature of skipper.

@szuecs I think what you are talking about should not be done in skipper. It's an HTTP router by design, so doing routing based on TLS is out of scope IMO.
