### ISSUE TITLE
Kubernetes ingress: allow to reduce request logging

### ISSUE THREAD

**Issue by vecmezoni** [zalando/skipper#750]
Currently, ingress skipper produces log entry for each request and for some of the services we want to be able to switch off extensive request logging.

**Comment by szuecs** [comment]
@vecmezoni can you explain how this should work in more detail, such that it's clear how this should work?

**Comment by vecmezoni** [comment]
Let's imagine that we will have `accessLog` filter and I would be able to disable access logs like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    zalando.org/skipper-filter: accessLog("false")
  name: app
spec:
  rules:
  - host: app-default.example.org
    http:
      paths:
      - backend:
          serviceName: app-svc
          servicePort: 80
``` 
or provide custom log format:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    zalando.org/skipper-filter: accessLog("remote_host - - [date] "method uri" status")
  name: app
spec:
  rules:
  - host: app-default.example.org
    http:
      paths:
      - backend:
          serviceName: app-svc
          servicePort: 80
```
