### ISSUE TITLE
How to route traffic from "example.com/inner-path" on a multi-host ingress?

### ISSUE THREAD

**Issue by nicroto** [zalando/skipper#773]
I have the following ingress:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
...
spec:
  rules:
  - host: "example.com"
    http:
      paths:
      - backend:
          serviceName: "web-front-service"
          servicePort: 80
  - host: "api.example.com/v1" # <-- THE PROBLEM
    http:
      paths:
      - backend:
          serviceName: "api-gateway-service"
          servicePort: 80
```

This is part of a helm chart and trying to install it, gives the following error:

```
Invalid value: "api.example.com/v1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'test.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

I know about the Path method but it seems to be only for the entire ingress and couldn't be applied on an ingress.host level?

Your help is much appreciated.

**Comment by nicroto** [comment]
Solved it. Had nothing to do with skipper. Sorry about this.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
...
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: web-front-service
          servicePort: 80
  - host: api.example.com
    http:
      paths:
        - path: /v1
          backend:
            serviceName: api-gateway-service
            servicePort: 80
```
