### ISSUE TITLE
Max loopbacks reached with multiple ingresses pointing to the same hostname

### ISSUE THREAD

**Issue by greenboxal** [zalando/skipper#831]
We were migrating a service to a different ingress (but the same hostname/path) and, temporarily had both the old and the new ingresses running on the cluster. We kept both so we wouldn't have any downtime. When testing, we detected that some requests were being dropped.

# Steps to reproduce
1. Create a deployment with a service
2. Create an ingress with the hostname `X`, pointing to that service
3. Create another ingress with the same hostname `X`, pointing to the same service

# Expected behavior
The requests would be routed based on some algorithm to the correct backend. Which algorithm is not relevant to this issue, it could be anything.

# Actual behavior
_Some_ requests failed and Skipper returned a 500. On the logs, we had this:
```
[APP]time="2018-10-31T23:52:24Z" level=error msg="error while proxying, route kube_e_core_production__core_production_xxxxxxxxx__network_xxxxxxxxx___xxxxxxxxxxxxx__lb_group, status code 500: max loopbacks reached"
```

**Comment by szuecs** [comment]
I think the problem is that the routing flaps between both `*_lb_group` routes -> max loopback

**Comment by greenboxal** [comment]
@szuecs do you have any idea on how to fix it? we can work on that

**Comment by szuecs** [comment]
@greenboxal I looked into it with my phone yesterday, but @aryszka told me that he will fix it.
I think the real fix is https://github.com/zalando/skipper/issues/689#issuecomment-426021387 or even a bigger enhancement as stated in https://github.com/zalando/skipper/issues/556.

**Comment by aryszka** [comment]
creating now a test to reproduce this bug

**Comment by aryszka** [comment]
not luck so far. @greenboxal , can you share the two ingress specs?

**Comment by greenboxal** [comment]
Sure, try the following:

Ingress 1:
```{
  "kind": "Ingress",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "svc-old",
    "namespace": "default",
    "labels": {
      "app": "svc",
      "chart": "svc-1.0.0",
      "heritage": "Tiller",
      "release": "prd-svc"
    },
    "annotations": {
      "kubernetes.io/ingress.class": "skipper-internet-facing"
    }
  },
  "spec": {
    "rules": [
      {
        "host": "svc.prd.myapp.com",
        "http": {
          "paths": [
            {
              "path": "/",
              "backend": {
                "serviceName": "svc-old",
                "servicePort": "http"
              }
            }
          ]
        }
      }
    ]
  }
}```

Ingress 2:
Sure, try the following:

Ingress 1:
```{
  "kind": "Ingress",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "svc-new",
    "namespace": "default",
    "labels": {
      "app": "svc",
      "chart": "svc-1.0.0",
      "heritage": "Tiller",
      "release": "prd-svc"
    },
    "annotations": {
      "kubernetes.io/ingress.class": "skipper-internet-facing"
    }
  },
  "spec": {
    "rules": [
      {
        "host": "svc.prd.myapp.com",
        "http": {
          "paths": [
            {
              "path": "/",
              "backend": {
                "serviceName": "svc-new",
                "servicePort": "http"
              }
            }
          ]
        }
      }
    ]
  }
}```

**Comment by szuecs** [comment]
@greenboxal which skipper version are you running this test? 

I tried to reproduce it 

2x ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sszuecs-demo-kiac-1
spec:
  rules:
  - host: c1.kiac-test.teapot.zalan.do
    http:
      paths:
      - backend:
          serviceName: sszuecs-kiac-connect
          servicePort: 80

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sszuecs-demo-kiac-2
spec:
  rules:
  - host: c1.kiac-test.teapot.zalan.do
    http:
      paths:
      - backend:
          serviceName: sszuecs-kiac-backend
          servicePort: 80
```

2x service
```
apiVersion: v1
kind: Service
metadata:
  name: sszuecs-kiac-backend
spec:
  ports:
  - name: external
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    application: sszuecs-kiac-backend
  sessionAffinity: None
  type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: sszuecs-kiac-connect
spec:
  ports:
  - name: external
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    application: sszuecs-kiac-connect
  sessionAffinity: None
  type: ClusterIP
```

2x deployments
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: sszuecs-kiac
  name: sszuecs-kiac-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      application: sszuecs-kiac-connect
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: sszuecs-kiac-connect
    spec:
      containers:
      - args:
        - skipper
        - -inline-routes
        - '* -> latency(5) -> inlineContent("connect") -> <shunt>'
        image: registry.opensource.zalan.do/pathfinder/skipper:v0.10.112
        name: sszuecs-kiac-connect
        ports:
        - containerPort: 9090
          protocol: TCP


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: sszuecs-kiac
  name: sszuecs-kiac-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      application: sszuecs-kiac-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: sszuecs-kiac-backend
    spec:
      containers:
      - args:
        - skipper
        - -inline-routes
        - '* -> latency(5) -> inlineContent("backend") -> status(223) -> <shunt>'
        image: registry.opensource.zalan.do/pathfinder/skipper:v0.10.112
        imagePullPolicy: IfNotPresent
        name: sszuecs-kiac
        ports:
        - containerPort: 9090
          protocol: TCP
```

client test
```
% for i in $(seq 1 9); do curl -s https://c1.kiac-test.teapot.zalan.do/ ; echo ""; sleep 0.5; done
connect
connect
backend
connect
connect
backend
connect
connect
backend
```
