### ISSUE TITLE
east-west routes ambiguous for multi host ingress

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#850]
An ingress with more than one rules, that has different host definitions will create ambiguous routes internal routes:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
  namespace: default
spec:
  rules:
  - host: demo.example.org
    http:
      paths:
      - backend:
          serviceName: example
          servicePort: 80
  - host: demo2.example.org
    http:
      paths:
      - backend:
          serviceName: example2
          servicePort: 80
```
