### ISSUE TITLE
Poll TLS cert and keys from directories

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#851]
This could enable to read secrets from Kubernetes secrets and terminate https in skipper at dynamic workloads, where certificates/keys are created in skipper would detect these new created ones.

**Comment by szuecs** [comment]
Thanks @ch-dimitri , nice idea!

**Comment by arnisoph** [comment]
Well, what do you with short-living certs as those from let's encrypt? For this a native integration using the tls field in IngressSpec would be essential..

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prometheus
  annotations:
    kubernetes.io/ingress.class: skipper
spec:
  tls:
    - secretName: wildcard-example.com-cert
      hosts:
        - prometheus.example.com
  rules:
    - host: prometheus.example.com
      http:
        paths:
          - backend:
              serviceName: prometheus
              servicePort: 9090     
```
