### ISSUE TITLE
Understand 500 with v0.10.122

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#863]
In high traffic routes running in Kubernetes with the following flags, there were an increase of 500s that might be converted from 499 to 500 after updating version to v.0.10.122. 

```
          - "skipper"
          - "-kubernetes"
          - "-kubernetes-in-cluster"
          - "-address=:9999"
          - "-proxy-preserve-host"
          - "-serve-host-metrics"
          - "-enable-ratelimits"
          - "-experimental-upgrade"
          - "-metrics-exp-decay-sample"
          - "-kubernetes-https-redirect=true"
          - "-kubernetes-https-redirect-code=301"
          - "-kubernetes-ingress-class=skipper"
          - "-application-log-level=WARN"
          - "-access-log-disabled"
          - "-enable-connection-metrics"
          - "-backend-host-metrics"
          - "-route-backend-metrics"
          - "-support-listener=:9998"
          - "-metrics-flavour=prometheus"
          - "-serve-route-metrics"
          - "-route-response-metrics"  
```

Log that converted (?) from 499 to 500 after https://github.com/zalando/skipper/pull/857 (v0.10.110 ->  v0.10.122):

`*_lb_group with backend , status code 500: dialing failed false: unexpected EOF`

**Comment by roffe** [comment]
Setup looks like:

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-ingress-aws-controller
  namespace: ingress
  labels:
    application: kube-ingress-aws-controller
    component: ingress
    type: public
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-ingress-aws-controller
      component: ingress
      type: public
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: staging.kube-ingress-aws-controller
      labels:
        application: kube-ingress-aws-controller
        component: ingress
    spec:
      serviceAccountName: skipper-ingress
      containers:
      - name: controller
        image: registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.8.0
        args:
          - "-ingress-class-filter=skipper"
          - "-health-check-port=9999"
          - "-target-port=9999"
          - "-controller-id=kube-ingress-aws-controller"
        env:
        - name: AWS_REGION
          value: eu-west-1
```

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: skipper-ingress
  namespace: ingress
  labels:
    component: ingress
    type: public
spec:
  selector:
    matchLabels:
      component: ingress
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: skipper-ingress
      labels:
        app: skipper-ingress
        component: ingress
        type: public
    spec:
      hostNetwork: true
      serviceAccountName: skipper-ingress
      containers:
      - name: skipper-ingress
        image: registry.opensource.zalan.do/pathfinder/skipper:v0.10.122
        args:
          - "skipper"
          - "-kubernetes"
          - "-kubernetes-in-cluster"
          - "-address=:9999"
          - "-proxy-preserve-host"
          - "-serve-host-metrics"
          - "-enable-ratelimits"
          - "-experimental-upgrade"
          - "-metrics-exp-decay-sample"
          - "-kubernetes-https-redirect=true"
          - "-kubernetes-https-redirect-code=301"
          - "-kubernetes-ingress-class=skipper"
          - "-application-log-level=WARN"
          - "-access-log-disabled"
          - "-enable-connection-metrics"
          - "-backend-host-metrics"
          - "-route-backend-metrics"
          - "-support-listener=:9998"
          - "-metrics-flavour=prometheus"
          - "-serve-route-metrics"
          - "-route-response-metrics"
          - "-read-timeout-server=2m"
          - "-enable-dualstack-backend=false"
        resources:
          limits:
            memory: 400Mi
          requests:
            memory: 25Mi
        readinessProbe:
          httpGet:
            path: /kube-system/healthz
            port: 9999
          initialDelaySeconds: 5
          timeoutSeconds: 5
```
