### ISSUE TITLE
Response filter to redirect if backend response has status code >=500

### ISSUE THREAD

**Issue by futare1** [zalando/skipper#867]
I want to have a chosen redirect if the backend response status code is >= 500. 

A solution could be a specific responsefilter `redirectToGtStatus("https://example.org", 500)`, that would redirect to https://example.org with a temporary redirect `307`, only if the response status code is >= 500 from the backend.

## Original issue
Hi - I'm new to Skipper.  Can anyone please point me in the direction of an example to configure/redirect to static outage message page for when a backend received a >=500 status code instead of the "Bad Gateway" message?

**Scenario:**
outage.domain.local (httpd app serving outage message html content)
app.domain.local (httpd app)

app Ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "app-ingress"
  namespace: default
spec:
  rules:
  - host: "app.domain.local"
    http:
      paths:
      - path: /
        backend:
          serviceName: app-service
          servicePort: 80
```
Any help is appreciated.
Wikus

**Comment by szuecs** [comment]
Can you share the output of `curl -v https://app.domain.local/` please?
Is `domain.local` inside the cluster or a valid domain, that you hide from us?

**Comment by futare1** [comment]
Hi szuecs, `domain.local` is only an example.  'outage' is a simple web app with a static page for customers when we do maintenace.  `app` is the production web app.  Say during maintenance of production `app` , a >=500 is returned and I wish to know how to redirect to the `outage` 

(in hindsight I should have referred to it as maintenance instead of outage).

**Comment by szuecs** [comment]
From what I understand you would like to do:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "app-ingress"
  namespace: default
    zalando.org/skipper-routes: |                                                                                       
       simpleredirect: PathRegexp("/") -> redirectTo(307, "https://outage.domain.local/") -> <shunt>;      
spec:
  rules:
  - host: "app.domain.local"
    http:
      paths:
      - path: /
        backend:
          serviceName: app-service
          servicePort: 80
```

You would get another route which is more specific (+1 Predicate PathRegexp()) then the route from the ingress spec. The more specific route would do the redirect as specified.
