### ISSUE TITLE
zalando.org/skipper-routes get applied to all ingress paths

### ISSUE THREAD

**Issue by dlmiddlecote** [zalando/skipper#873]
Hi,

I'm trying to add a simple redirect to a kubernetes ingress, and I'm having trouble with it.

Sample Ingress:
```yaml
apiVersion: extensions/v1beta1                                                                                          
kind: Ingress                                                                                                           
metadata:                                                                                                               
  name: skipper-ingress                                                                                         
  annotations:                                                                                                          
    kubernetes.io/ingress.class: skipper                                                         
    zalando.org/skipper-routes: |                                                                                       
       simpleredirect: Path("/foo/") -> redirectTo(308, "/bar/") -> <shunt>;                                                         
  spec:                                                                                                                   
    rules:                                                                                                                
      - host: foo.bar
        http:                                                                                                             
          paths:                                                                                                          
            - path: /something/                                                                                                
              backend:                                                                                                    
                serviceName: something                                                                                      
                servicePort: 80                                                                                           
            - path: /else/                                                                                               
              backend:                                                                                                    
                serviceName: else                                                                                      
                servicePort: 80 
```

My expectation here is that the routes generated would be:
* `Host(/^foo[.]bar$/) && PathRegexp(/^\/something\//) -> 10.*.*.*`
* `Host(/^foo[.]bar$/) && PathRegexp(/^\/else\//) -> 10.*.*.*`
* `Host(/^foo[.]bar$/) && Path("/foo/") -> redirectTo(308, "/bar/") -> <shunt>`

However, I am seeing these routes:
* `Host(/^foo[.]bar$/) && PathRegexp(/^\/something\//) -> 10.*.*.*`
* `Host(/^foo[.]bar$/) && PathRegexp(/^\/else\//) -> 10.*.*.*`
* `Path("/foo/") && Host(/^foo[.]bar$/) && PathRegexp(/^\/something\//) -> redirectTo(308, "/bar/") -> <shunt>`
* `Path("/foo/") && Host(/^foo[.]bar$/) && PathRegexp(/^\/else\//) -> redirectTo(308, "/bar/") -> <shunt>`

This means that the custom route cannot ever be picked up.

From the docs it looks like this should be possible - https://opensource.zalando.com/skipper/kubernetes/ingress-usage/#multiple-routes

Any help would be greatly appreciated.
