### ISSUE TITLE
Ingress Path Matching - Default Backends - convertDefaultBackend

### ISSUE THREAD

**Issue by Shareed2k** [zalando/skipper#930]
Hi i want to create default ingress and use nginx default backend image "k8s.gcr.io/defaultbackend" as 404 responser 

and also use annotations filters, but as i see in /routes, there is no filter definitions at all
`
kube_devops__default_ing_skipper_______0: *
  -> "http://172.18.1.11:8080";
`

and skipper logs repeted again and again
```shell
skipper [APP]time="2019-01-23T14:02:53Z" level=info msg="Found target port 8080, for service skipper-default-http-backend"
skipper-nw592 skipper [APP]time="2019-01-23T14:02:53Z" level=info msg="convertDefaultBackend: Found 1 endpoints for skipper-default-http-backend: <nil>"
```

my default ingress

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default-ing-skipper
  annotations:
    kubernetes.io/ingress.class: skipper
    zalando.org/skipper-filter: bringgRateLimit()

spec:
  backend:
    serviceName: skipper-default-http-backend
    servicePort: 8080
```
