### ISSUE TITLE
Kubernetes: update Ingress status field

### ISSUE THREAD

**Issue by ch-dimitri** [zalando/skipper#931]
When using a `LoadBalancer` Service to provision the frontend to Skipper, it should update the `status` field of Ingress objects assigned to that ingress-class.  ingress-nginx does [this](https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/status/status.go#L349-L372).

Skipper should do something similar for cases that don't use the [AWS Ingress Controller|https://github.com/zalando-incubator/kube-ingress-aws-controller], but instead rely upon the native cloud provider.

Example config:
```
kind: Service
apiVersion: v1
metadata:
  name: skipper-ingress
  namespace: kube-system
  labels:
    app.kubernetes.io/name: skipper-ingress
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-type: nlb                                                                                                                                                                                                                                                                                                                 
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    application: skipper-ingress
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
```
