### ISSUE TITLE
clientRatelimit is not recognised as a valid route filter

### ISSUE THREAD

**Issue by irishshagua** [zalando/skipper#943]
Build 0.10.159 of Skipper is not recognising [clientRatelimit](https://opensource.zalando.com/skipper/reference/filters/#clientratelimit) as a valid filter name:

Example Skiper K8s resource:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    zalando.org/skipper-filter: clientRatelimit(600, "1m")
    zalando.org/skipper-predicate: Path("/routeC") && Method("GET")
  name: fgtestapp-route-c
  namespace: default
spec:
  rules:
    - host: rl-fgtestapp.smart-product-platform-test.zalan.do
      http:
        paths:
          - backend:
              serviceName: fgtestapp
              servicePort: http
```

Error logs from skipper:
```
{"log":"[APP]time=\"2019-02-06T11:41:58Z\" level=error msg=\"failed to process route (kubeew_default__fgtestapp_route_c__rl_fgtestapp_smart_product_platform_test_zalan_do____fgtestapp_0): filter not found: 'clientRatelimit'\"\n","stream":"stderr","time":"2019-02-06T11:41:58.075145532Z"}
```
