### ISSUE TITLE
Ingress: Handle overlapping ingress definitions in a deterministic way

### ISSUE THREAD

**Issue by mikkeloscar** [zalando/skipper#962]
Imagine you have the following ingresses defined:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-live
spec:
  rules:
  - host: app.example.org
    http:
      paths:
      - backend:
          serviceName: app-live
          servicePort: 80
```

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-dev
spec:
  rules:
  - host: app.example.org
    http:
      paths:
      - backend:
          serviceName: app-dev
          servicePort: 80
```

In this case skipper will create two routes like this:

```
kube_default__app_live__app_example_org____app_live:
  Host(/^app[.]example[.]org$/)
  -> <roundRobin, "http://10.2.0.3:9090">;

kube_default__app_dev__app_example_org____app_dev:
  Host(/^app[.]example[.]org$/)
  -> <roundRobin, "http://10.2.1.3:9090">;
```

Because both routes have the same Host predicate it will route to either randomly.

It would be good if we could make this deterministic such that for instance the oldest ingresses resource wins and the second resource doesn't get routes generated if it would overlap. This would make it simpler to debug and prevent incidents where users accidentally deploy an overlapping ingress resource messing with a live service.

Note that host predicate alone is not always the determining factor, their might be predicates or routes defined via annotations on the ingress, which would make it overlap or not. Things like `PathRegexp()` predicate could also overlap in less obvious ways, but maybe we don't need to cover all edge cases, at least not in the first iteration.
