### ISSUE TITLE
Prometheus route metrics still available after deleting route

### ISSUE THREAD

**Issue by wndhydrnt** [zalando/skipper#965]
While working with Skipper, I recognized that metrics of deleted routes are still exposed on the Prometheus endpoint "/metrics".

traefik faced a similar issue and documented their solution in the source code[1].
There is also a question regarding obsolete metrics in the prometheus-users group[2].

1: https://github.com/containous/traefik/blob/a09dfa3ce10f222ab6e10ac11386d330698ff6f8/metrics/prometheus.go#L48-L59
2: https://groups.google.com/d/msg/prometheus-users/EbumSJYsJyc/wvdL_NqqAAAJ

---

## Steps to reproduce

1. I'm running Skipper Version 2c45dcac04f8e6e4da6891eacd0f9592942192cc (built and executed locally) and Kubernetes v1.11.6 on minikube
2. Deploy an application:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-prod
  labels:
    app: web
    release: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      release: prod
  template:
    metadata:
      labels:
        app: web
        release: prod
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: web-service-prod
spec:
  selector:
    app: web
    release: prod
  ports:
  - protocol: TCP
    port: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: skipper
  name: web-ingress
spec:
  rules:
  - host: web.dev.local
    http:
      paths:
      - backend:
          serviceName: web-service-prod
          servicePort: 80
        path: /
```
3. Send a request to the application: `curl -i -H'Host: web.dev.local' 127.0.0.1:9999`
4. Check the "/metrics" endpoint of Skipper. Metrics like the following are exposed:
```
skipper_response_duration_seconds_sum{code="200",method="GET",route="kube_default__web_ingress__web_dev_local_____web_service_prod"} 0.000525136
skipper_response_duration_seconds_count{code="200",method="GET",route="kube_default__web_ingress__web_dev_local_____web_service_prod"} 1
```
5. Delete the Ingress: `kubectl delete ingress web-ingress`
6. Check the "/metrics" endpoint of Skipper again.

### Expected result

No metrics with the route ID `kube_default__web_ingress__web_dev_local_____web_service_prod` are exported.

### Actual result
All metrics with the route ID `kube_default__web_ingress__web_dev_local_____web_service_prod` are still exported.
